[package]
name = "toysnes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = {version = "1.1.0", features = ["serde"]}
bitmatch = "0.1.1"
modular-bitfield = "0.11.2"
once_cell = "1.10.0"