name: release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            
            - uses: actions/setup-node@v1
              with:
                  node-version: 18

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: aarch64-apple-darwin

            - run: cargo build --release --target aarch64-apple-darwin
